/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const AWS_MOBILE = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:248a838a-596b-4aa3-86e0-3a5f28f8da65",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_tEEgN0hUu",
    "aws_user_pools_web_client_id": "gtjuqfssqm5os3ee75gcghgt4",
    "oauth": {}
};


